# Generated by Django 5.0.3 on 2024-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupas', '0002_alter_marca_id_alter_marca_nome_alter_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='loja/imagem'),
        ),
    ]
